import os

## APP
INTRA_APP_PUBLIC = os.getenv("INTRA_APP_PUBLIC")
INTRA_APP_SECRET = os.getenv("INTRA_APP_SECRET")
HOMEMAKER_ENDPOINT=os.getenv("HOMEMAKER_ENDPOINT")
HOMEMAKER_TOKEN = os.getenv("HOMEMAKER_TOKEN")

##
PERCHECK_TIME_IN_SEC = int(os.getenv("PERCHECK_TIME_IN_SEC"))